### ISSUE TITLE
Moved to new Github organization "everywall" 

### ISSUE THREAD

**Issue by mms-gianni** [everywall/ladder#22]
Hey everyone

I moved the ladder to its own Github organization, to avoid conflicts with my other side project Kubero.

Pulling docker images from the old organization is still possible. But you better use the new organization: 

```
docker pull ghcr.io/everywall/ladder:latest 
``` 

I also opened the [Discussions](https://github.com/everywall/ladder/discussions) to have a more convenient method to address topics an general discussions.

**Comment by mms-gianni** [comment]
Currently having some issues with releasing binaries: v0.0.15 and v0.0.16 to the new Organization.

**Comment by mms-gianni** [comment]
Phuu. Build is fixed.

**Comment by bradym** [comment]
Getting access denied errors when attempting to pull docker images from the new org.

```
$ docker run -p 8080:8080 -d --name ladder ghcr.io/everywall/ladder:latest 
Unable to find image 'ghcr.io/everywall/ladder:latest' locally
docker: Error response from daemon: denied.
```

Checked the logs for the latest docker build job on github actions and saw the image was tagged as `ghcr.io/everywall/ladder:0.0.16-1` so I tried pulling that one too:

```
$ docker pull ghcr.io/everywall/ladder:0.0.16-1
Error response from daemon: denied
```

**Comment by deoxykev** [comment]
Same issue here.

docker: Error response from daemon: Head "https://ghcr.io/v2/everywall/ladder/manifests/latest": unauthorized.

---
@mms-gianni

Can you check if everywall/ladder GHCR is set to public? 
GitHub repository settings > Packages  > visibility settings

**Comment by mms-gianni** [comment]
O damn. I did test this but obviously worked for me. 

changed to public. 
thx @bradym and @deoxykev

**Comment by some-guy-23** [comment]
@mms-gianni not sure about others, but I'm still getting the same unauthorized header?

`failed to pull images of the stack:  ladder Pulling ladder Error Error response from daemon: Head "https://ghcr.io/v2/everywall/ladder/manifests/latest": unauthorized`

**Comment by mms-gianni** [comment]
@some-guy-23 Strange. It was still private. 

Can you check it again please?

**Comment by some-guy-23** [comment]
@mms-gianni success, thank you!

**Comment by mms-gianni** [comment]
Phuu. This org migration was thing. 

Hope everything works now.
